import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SiteProvider } from "@/SiteContext/SiteProvider";
import { BargerMenu } from "@/Components/Bargermenu/BargerMenu"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

import { Roboto } from 'next/font/google';
import "@/css/style.css"
// const roboto = Roboto({
//   subsets: ['latin'],
//   weight: ['400', '700'], // You can choose weights
//   display: 'swap',
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Add Google Fonts in head */}
        <link
          href="https://fonts.googleapis.com/css2?family=Days+One&family=Dosis&family=Quicksand&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Dosis:wght@600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body >
        <SiteProvider>
        <BargerMenu />
        {children}
        </SiteProvider>
      </body>
    </html>
  );
}
